name = "WrappedUnions"
uuid = "325db55a-9c6c-5b90-b1a2-ec87e7a38c44"
authors = ["Adriano Meligrana <adrianomeligrana@proton.me>"]
version = "0.3.2"

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "BenchmarkTools", "Test"]
